version: '3.9'

services:
  db:
    image: mysql:5.7
    container_name: "${PROJECT_NAME}-db"
    restart: always
    ports:
      - "${DB_PORT}:3306"
    networks:
      - starfish
    environment:
      MYSQL_ROOT_PASSWORD: "${PASSWORD}"
      MYSQL_DATABASE: "${PROJECT_NAME}-db"
      MYSQL_USER: "${USER}"
      MYSQL_PASSWORD: "${PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
  wordpress:
    depends_on:
      - db
    image: wordpress:5.9.3-fpm
    container_name: "${PROJECT_NAME}-wp"
    restart: always
    links:
      - db
    networks:
      - starfish
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: "${USER}"
      WORDPRESS_DB_NAME: "${PROJECT_NAME}-db"
      WORDPRESS_DB_PASSWORD: "${PASSWORD}"
      WORDPRESS_DEBUG: "${DEBUG}"
    working_dir: /var/www/html
    volumes:
      - ./html:/var/www/html/
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:latest
    container_name: "${PROJECT_NAME}-nginx"
    networks:
      - starfish
    depends_on:
      - wordpress
    ports:
      - "${PORT}:80"    # http
    volumes:
      - ./html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
  phpmyadmin:
    container_name: "${PROJECT_NAME}-wpa"
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8090:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "${PASSWORD}"
    networks:
      - starfish
volumes:
  db_data:
networks:
  starfish:
    driver: bridge